### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by WilsonMonkey** [Canbanizers/Canban#116]
Hi Guys(Jan^^),

please create branches for all the stuff you will be comitting the next few days, otherwise we will fuck up our repo before the deadline.
And please don't commit crap like comments, testing stuff etc. 

In general we should communicate in a better way, because there are some bugs and features which are worked on by two people at the same time. This isn't very productive.
Maybe we should meet together if I'm back. Unfortunatily the wlan here is limited and I can't do a lot of stuff for our project.
In doubt please call each other.

**Comment by WilsonMonkey** [comment]
Info: I will refactor the backend the next few days, so there will be major changes. Also i will look for a hoster for our app.

**Comment by janz93** [comment]
Okay sorry for not commiting it into a branch.
Since I only change minor things I thought it's not needed of pushing them into an branch or even open an ticket for some changes.
I think as we (Willy and I) already discussed on friday it would be good to meet on Wednessday and discuss on how we will proceed the next days.
